name: "Setup and Run Tests"
description: "Sets up the Python environment and runs tests with tox"

inputs:
  UV_INDEX:
    description: "The URL(s) for the Python package index, including any authentication"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        enable-cache: "true"

    - name: Install tox
      shell: bash
      run: uv tool install tox --with tox-uv

    - name: Run tests with tox
      shell: bash
      env:
        UV_INDEX: ${{ inputs.UV_INDEX }}
        UV_NO_CACHE: "1"
      run: uv run tox

