name: "Dependency Vulnerability Check"
description: "Runs pip-audit to check for dependency vulnerabilities"

inputs:
  python_version:
    description: "The version of Python to use"
    required: false
    default: "3.9"
  
  working_directory:
    description: "Working directory for the Python project (useful for monorepos)"
    required: false
    default: "."
  
  pip_audit_version:
    description: "Version of pip-audit to install (defaults to latest)"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: gold-standard-phantoms/github-actions/.github/actions/setup-python@v0.3.0
      with:
        UV_INDEX: ${{ inputs.UV_INDEX }}
        python_version: ${{ inputs.python_version }}
        install_deps: "true"
        install_dev_deps: "true"
        working_directory: ${{ inputs.working_directory }}

    - name: Generate requirements with uv
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        # Try to compile from pyproject.toml first, fallback to pip freeze
        if [ -f "pyproject.toml" ]; then
          uv pip compile pyproject.toml -o requirements.txt || uv pip freeze > requirements.txt
        else
          echo "No pyproject.toml found, using pip freeze"
          uv pip freeze > requirements.txt
        fi

    - name: Create virtual environment
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: uv venv

    - name: Install pip-audit (specific version)
      if: ${{ inputs.pip_audit_version != '' }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: uv pip install pip-audit==${{ inputs.pip_audit_version }}

    - name: Install pip-audit (latest)
      if: ${{ inputs.pip_audit_version == '' }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: uv pip install pip-audit

    - name: Run pip-audit
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: uv run pip-audit -r requirements.txt

